export default [
  'News',
  'Life Style',
  'Book Recommendations',
  'Random',
  'Product Review',
  'Development',
  'Legal',
  'Marketing',
  'SEO',
  'Market Research',
  'Cloud Computing',
  'Cybersecurity',
  'Artificial Intelligence',
  'Blockchain',
  'Fundraising',
  'Finances',
  'Productivity',
  'Health and Wellness',
  'Networking',
  'Sustainability',
  'Customer Experience',
  'Self-Education',
  'Growth Strategies',
  'Analytics and Reporting',
  'Shipping and Fulfillment',
  'No-code',
  'Low-code',
]